<!DOCTYPE html>
<html>
   <head>
      <title>HTML Meta Tag</title>
      <meta http-equiv = "refresh" content = "2; url = https://fshirani2006.github.io/" />
   </head>
   <body>
      <p>Redirecting.</p>
   </body>
</html>
